src/CloudOCR/CloudOCR/Controllers/AplicationController.cs
using CloudOCR.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace CloudOCR.Controllers
{
    public class AplicationController : Controller
    {
        //
        // GET: /Aplication/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Aplicacion()
        {
            return View();
        }

        public ActionResult editUser()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FileUpload(IEnumerable<HttpPostedFileBase> files)
        {
            foreach (var file in files)
                 if (file != null)          
                {
                    ApplicationDbContext db = new ApplicationDbContext();
                    string ImageName = System.IO.Path.GetFileName(file.FileName);
                    string physicalPath = Server.MapPath("~/Content/Images/" + ImageName);

                    // save image in folder
                    file.SaveAs(physicalPath);

                    //save new record in database
                    PicturesViewModel newRecord = new PicturesViewModel();
                    newRecord.flName = ImageName;
                    newRecord.url = physicalPath;
                    db.PicturesSet.Add(newRecord);
                    db.SaveChanges();

                }
            //Display records
            return RedirectToAction("../Aplication/Aplicacion/");
        }

    }

}

src/CloudOCR/CloudOCR/Views/Shared/_Layout.cshtml
@{
    ViewBag.Title = "Inicio";
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CloudOCR</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CloudOCR", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Aplicación", "Index", "Aplication")</li>
                        <li>@Html.ActionLink("Admin", "Index", "Account")</li>
                    }
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Luis René Salas López</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>